let strip = neopixel.create(DigitalPin.P1, 10, NeoPixelMode.RGB)
strip.setBrightness(10)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Indigo))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    for (let index = 0; index < 32; index++) {
        basic.pause(100)
        strip.rotate(1)
        strip.show()
    }
    strip.clear()
    for (let index = 0; index < 4; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Purple))
        basic.pause(200)
    }
    strip.clear()
})
